name: CI

on:
  push:
    branches-ignore:
      - 'release-*'
    tags-ignore:
      - '*.*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Run checks
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y bzr || true
          make ci
